# Generated by Django 2.1.3 on 2018-11-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
